name: ChamaVote
version: @version@
main: click.seichi.chamavote.ChamaVote
depend:
  - WorldGuard

commands:
  cvote:
    usage: /cvote
    description: This is the command to vote to the region where you are standing.
    default: true
  cdeletevotes:
    usage: /cdeletevotes
    description: This is the command to delete all votes.
    permission: chamavote.cdeletevotes
  ctotalvotes:
    usage: /ctotalvotes
    description: This is the command to total votes.
    permission: chamavote.ctotalvotes
